# Generated by Django 5.2 on 2025-05-02 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_team_1', models.IntegerField(default=0)),
                ('score_team_2', models.IntegerField(default=0)),
                ('map_played', models.CharField(choices=[('mirage', 'Mirage'), ('train', 'Train'), ('dust_2', 'Dust 2'), ('overpass', 'Overpass'), ('inferno', 'Inferno'), ('nuke', 'Nuke'), ('vertigo', 'Vertigo'), ('ancient', 'Ancient')], max_length=50)),
                ('round_number', models.IntegerField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('ongoing', 'Em andamento'), ('completed', 'Concluída'), ('cancelled', 'Cancelada')], default='pending', max_length=10)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='competitions.competition')),
                ('team_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_team_1', to='competitions.team')),
                ('team_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_team_2', to='competitions.team')),
            ],
            options={
                'db_table': 'matches',
                'ordering': ['start_time'],
            },
        ),
    ]
